openapi: 3.0.0
info:
  title: Mining Pools Mempool GraphQL API
  version: 1.0.0
paths:
  /graphql:
    post:
      summary: Execute GraphQL queries
      operationId: executeGraphQLQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The GraphQL query
                variables:
                  type: object
                  description: The variables for the GraphQL query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: The result of the GraphQL query
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/GraphQLError'

components:
  schemas:
    GraphQLError:
      type: object
      properties:
        message:
          type: string
          description: Description of the error
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'
    Location:
      type: object
      properties:
        line:
          type: integer
          description: Line number of the error in the GraphQL query
        column:
          type: integer
          description: Column number of the error in the GraphQL query
        path:
          type: array
          items:
            type: string
          description: Path to the field in the GraphQL query where the error occurred
