openapi: 3.0.0
info:
  title: Mining Pools Mempool API
  version: 1.0.0
paths:
  /mining/pools/24h:
    get:
      summary: Get mining pool statistics for the last 24 hours
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/miningpool"
   /api/address/{address}/utxo:
    get:
      summary: Get UTXOs for a specific address
      description: Returns the list of Unspent Transaction Outputs (UTXOs) for a given address
      parameters:
        - in: path
          name: address
          required: true
          schema:
            type: string
          description: The address for which to retrieve UTXOs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    txid:
                      type: string
                      description: The transaction ID of the UTXO
                    vout:
                      type: integer
                      description: The output index of the UTXO
                    status:
                      type: object
                      properties:
                        confirmed:
                          type: boolean
                          description: Indicates whether the UTXO is confirmed
                        block_height:
                          type: integer
                          description: The height of the block containing the UTXO
                        block_hash:
                          type: string
                          description: The hash of the block containing the UTXO
                        block_time:
                          type: integer
                          description: The timestamp of the block containing the UTXO
                      description: Status of the UTXO
                    value:
                      type: integer
                      description: The value of the UTXO in satoshis
              example:
                - txid: "5f3dafcdd142358b332e0939d37174b76472735df8df29325901d2c7d18a152c"
                  vout: 476
                  status:
                    confirmed: true
                    block_height: 834708
                    block_hash: "00000000000000000000292964b4b00d1d414583bd18d1ebea7a8041d4409c6d"
                    block_time: 1710447063
                  value: 546


  /lightning/nodes/countries:
    get:
      summary: Returns aggregate capacity and number of clearnet nodes per country.
      description: Capacity figures are in satoshis.
      operationId: getLightningNodesCountries
      responses:
        "200":
          description: An array of countries with their Lightning Network nodes statistics.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/countryNodeStats"
  
  /lightning/nodes/isp-ranking:
    get:
      summary: Returns aggregate capacity, number of nodes, and number of channels per ISP. Capacity figures are in satoshis.
      description: Capacity figures are in satoshis
      responses:
        "200":
          description: A list of arrays of ispRanking nodes info and three capacity statistics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ispRankingStats"

components:
  schemas:
    miningpool:
      type: object
      properties:
        pools:
          type: array
          items:
            $ref: "#/components/schemas/pool"
        blockCount:
          type: integer
          description: Total number of blocks mined in the last 24 hours
        lastEstimatedHashrate:
          type: number
          description: Last estimated hashrate

    pool:
      type: object
      properties:
        poolId:
          type: integer
          description: The unique ID of the pool
        name:
          type: string
          description: The name of the mining pool
        link:
          type: string
          format: uri
          description: The URL of the mining pool's website
        blockCount:
          type: integer
          description: Number of blocks mined by the pool in the last 24 hours
        rank:
          type: integer
          description: The ranking of the pool based on blocks mined in the last 24 hours
        emptyBlocks:
          type: integer
          description: Number of empty blocks mined by the pool in the last 24 hours
        slug:
          type: string
          description: A unique identifier for the pool
        avgMatchRate:
          type: number
          description: Average match rate of the pool's blocks in the last 24 hours
        avgFeeDelta:
          type: string
          description: Average fee delta of the pool's blocks in the last 24 hours
        poolUniqueId:
          type: integer
          description: The unique ID of the pool

    countryNodeStats:
      type: object
      properties:
        name:
          type: object
          properties:
            de: { type: string }
            en: { type: string }
            es: { type: string }
            fr: { type: string }
            ja: { type: string }
            pt-BR: { type: string }
            ru: { type: string }
            zh-CN: { type: string }
        iso:
          type: string
        count:
          type: integer
        share:
          type: number
          format: float
        capacity:
          type: string
          
    ispRankingStats:
      type: object
      properties:
        clearnetCapacity:
          type: integer
        torCapacity:
          type: integer
        unknownCapacity:
          type: integer
        ispRanking:
          type: array
          items:
            type: array
            items:
              anyOf:
                - type: string
                - type: integer
#

 